services:
  fff_proxy:
    image: fff_proxy:latest
    build: .
    ports:
      - "23000:23000"
    volumes:
      - ./Certs:/home/fff_proxy/certs:ro
    restart: on-failure
    tmpfs:
      - /tmp:rw,size=1g,mode=1777
